<div id="custom-delivery-popup-modal" class="custom-delivery-popup-modal">
    <div class="delivery popup title">
        <span><?= __("FIND YOUR LOCAL CAKE BOX")?></span>
    </div>
    <div class="delivery popup content">
        <div class="delivery popup text"><span><?= __("Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque")?></span>
        </div>
        <form class="delivery popup postcode" action="<?php echo $block->escapeUrl($block->postCode()) ?>" formKey ="<?php echo $block->getFormKey();?>" method="POST" >
            <input class="input postcode" type="text" name="postcode" placeholder = "Enter Postcode">
            <div class="selects collection">
                <div class="free collection" type="submit" >
                    <button><?= __("Free Collection")?></button>
                </div>
                <div class="premium delivery">
                    <button><?= __("Premium Delivery")?></button>
                </div>
                <div class="express one hour collection">
                    <button><?= __("Express 1 Hour Collection")?></button>
                </div>
            </div>
        </form>
    </div>
</div>

<script>

</script>
<script type="text/x-magento-init">
    {
    ".custom-delivery-popup-modal":
        {
            "X247Commerce_DeliveryPopUp/js/deliverypopup": {
            }
        }
    }
</script>