<?php 
/** @var $block \X247Commerce\DeliveryPopUp\Block\Location $block */ 
?>

<div id="custom-delivery-popup-modal" class="custom-delivery-popup-modal">
    <div class="amlocator-map-container" id="map-container-delivery-popup">
        <div class="delivery popup title">
            <span><?= __("FIND YOUR LOCAL CAKE BOX")?></span>
        </div>
        <div class="delivery popup content">
            <div class="delivery popup text"><span><?= __("Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque")?></span>
            </div>
            <form class="delivery popup postcode" action="<?php echo $block->escapeUrl($block->postCode()) ?>" formKey ="<?php echo $block->getFormKey();?>" method="POST" >
                <input class="input postcode" type="text" name="postcode" placeholder="Enter Postcode">
                
            </form>
        </div>
        
        <div class="amlocator-wrapper">
            <input type="text" value="" class="amlocator-text"
                   name="address" placeholder="<?= $block->escapeHtml(__('Current location')); ?>"
                   data-amlocator-js="address"
                   autocomplete="off">
            <span class="amlocator-search" data-amlocator-js="search"></span>
            <span class="amlocator-reset -hidden" data-amlocator-js="reset"></span>
        </div>
        <div class="selects collection">
            <div class="free collection" type="submit" >
                <button><?= __("Free Collection")?></button>
            </div>
            <div class="premium delivery">
                <button><?= __("Premium Delivery")?></button>
            </div>
            <div class="express one hour collection">
                <button><?= __("Express 1 Hour Collection")?></button>
            </div>
        </div>

        <div class="amlocator-block -search amlocator-search-radius">
            <input
                    data-amlocator-js="radius-value"
                    name="radius"
                    type="hidden"
                    id="amlocator-search-radius"
                    value="<?= (int) $block->getSearchRadius() ?>">
            <input
                    data-amlocator-js="radius-measurment"
                    name="measurement"
                    type="hidden"
                    id="amlocator-measurement"
                    value="<?= $block->escapeHtml($block->getDistanceConfig()) == 'km' ? 'km' : 'mi' ?>">
        </div>
        <div class="amlocator-block -storelist amlocator-store-list">
            <?= $block->getLeftBlockHtml(); ?>
        </div>
        <div class="amlocator-block -separator"><hr class="hr"/></div>
        <div class="amlocator-block -map" style="display: none;">
            <div class="amlocator-map" id="<?= $block->escapeHtml($block->getMapId()); ?>"></div>
        </div>
    
    </div>

    <script>
    require([
        'jquery',
        'X247Commerce_DeliveryPopUp/js/locator',
        'Amasty_Storelocator/js/cluster',
        'domReady!',
        'mage/loader',
        'https://maps.googleapis.com/maps/api/js?libraries=places&key=<?= $block->escapeHtml(
            $block->configProvider->getApiKey()
        ); ?>'
    ], function ($) {
        var mapId =  "<?= '#' . $block->escapeHtml($block->getMapId()); ?>",
            $body = $('body'),
            isLoaderAjaxInitiated = !!$.data($body.get(0), 'mage-loader'),
            isLoaderInitiated = isLoaderAjaxInitiated,
            initFunction,
            tryToInit = function () {
                if (isLoaderInitiated && isLoaderAjaxInitiated) {
                    initFunction();

                    return true;
                }

                return false;
            };

        initFunction = function () {
            $(mapId).amLocator({
                amMediaUrl :"<?= $block->escapeHtml($block->getAmStoreMediaUrl()); ?>",
                mapZoom: <?= $block->escapeHtml($block->getMapZoom()); ?>,
                automaticLocate: "<?= (bool)$block->getAutomaticLocate(); ?>",
                enableClustering: 0,
                enableSuggestionClickSearch: "<?= (bool)$block->getSuggestionClickSearch(); ?>",
                enableCountingDistance: "<?= (bool)$block->getCountingDistance(); ?>",
                distanceConfig: "<?= $block->escapeHtml($block->getDistanceConfig()); ?>",
                useGeoConfig: "<?= (bool)$block->getGeoUse()?>",
                allowedCountries: <?= /* @noEscape */ $block->getAllowedCountries(); ?>,
                ajaxCallUrl: "<?= $block->escapeHtml(
                    $block->getUrl('amlocator/index/ajax') . $block->getQueryString()
                ); ?>",
                useBrowserLocation: "<?= (bool)$block->getUseBrowserLocation()?>",
                jsonLocations: <?= /* @noEscape */ $block->getJsonLocations() ?>,
                imageLocations: "<?= $block->escapeHtml($block->getViewFileUrl('Amasty_Storelocator::images/')); ?>",
                mapId : "<?= $block->escapeHtml($block->getMapId()); ?>",
                mapContainerId: "<?= $block->escapeHtml($block->getMapContainerId()); ?>",
                showSearch: 1
            });
        };

        tryToInit();
        $body.on('loadercreate', function () {
            isLoaderInitiated = true;
            tryToInit();
        }).on('loaderajaxcreate', function () {
            isLoaderAjaxInitiated = true;
            tryToInit();
        });
    })
    </script>

</div>

<script type="text/x-magento-init">
    {
    ".custom-delivery-popup-modal":
        {
            "X247Commerce_DeliveryPopUp/js/deliverypopup": {}
        }
    }
</script>