<?php
/**
 * Copyright ©  All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

namespace X247Commerce\HolidayOpeningTime\Model;

use Magento\Framework\Model\AbstractModel;
use X247Commerce\HolidayOpeningTime\Api\Data\StoreLocationHolidayInterface;

class StoreLocationHoliday extends AbstractModel
{
    const ID = 'id';
    const TITLE = 'title';
    const OPEN_TIME = 'open_time';
    const CLOSED_TIME = 'closed_time';
    const DISABLE_DELIVERY = 'disable_delivery';
    const DISABLE_PICKUP = 'disable_pickup';
    const STORE_LOCATION_ID = 'store_location_id';


    /**
     * @inheritDoc
     */
    public function _construct()
    {
        $this->_init(\X247Commerce\HolidayOpeningTime\Model\ResourceModel\StoreLocationHoliday::class);
    }


    /**
     * @inheritDoc
     */
    public function getId()
    {
        return $this->getData(self::ID);
    }

    /**
     * @inheritDoc
     */
    public function setId($id)
    {
        return $this->setData(self::ID, $id);
    }

    /**
     * @inheritDoc
     */
    public function getTitle()
    {
        return $this->getData(self::TITLE);
    }

    /**
     * @inheritDoc
     */
    public function setTitle($title)
    {
        return $this->setData(self::TITLE, $title);
    }

    /**
     * @inheritDoc
     */
    public function getDate()
    {
        return $this->getData(self::DATE);
    }

    /**
     * @inheritDoc
     */
    public function setDate($date)
    {
        return $this->setData(self::DATE, $date);
    }

    /**
     * @inheritDoc
     */
    public function getOpenTime()
    {
        return $this->getData(self::OPEN_TIME);
    }

    /**
     * @inheritDoc
     */
    public function setOpenTime($openTime)
    {
        return $this->setData(self::OPEN_TIME, $openTime);
    }

    /**
     * @inheritDoc
     */
    public function getClosedTime()
    {
        return $this->getData(self::CLOSED_TIME);
    }

    /**
     * @inheritDoc
     */
    public function setClosedTime($closedTime)
    {
        return $this->setData(self::CLOSED_TIME, $closedTime);
    }

    /**
     * @inheritDoc
     */
    public function getDisableDelivery()
    {
        return $this->getData(self::DISABLE_DELIVERY);
    }

    /**
     * @inheritDoc
     */
    public function setDisableDelivery($disableDelivery)
    {
        return $this->setData(self::DISABLE_DELIVERY, $disableDelivery);
    }

    /**
     * @inheritDoc
     */
    public function getDisablePickup()
    {
        return $this->getData(self::DISABLE_PICKUP);
    }

    /**
     * @inheritDoc
     */
    public function setDisablePickup($disablePickup)
    {
        return $this->setData(self::DISABLE_PICKUP, $disablePickup);
    }

    /**
     * @inheritDoc
     */
    public function getStoreLocationId()
    {
        return $this->getData(self::STORE_LOCATION_ID);
    }

    /**
     * @inheritDoc
     */
    public function setStoreLocationId($storeLocationId)
    {
        return $this->setData(self::STORE_LOCATION_ID, $storeLocationId);
    }

    public function afterLoad()
    {
        return parent::afterLoad(); // @TODO: Change the autogenerated stub
    }

}

