<div class="trustpilot-header full-width">
	<div class="trustpilot-header-wrapper">
		<!-- TrustBox widget - Micro Star -->
		<div class="trustpilot-widget" data-locale="en-GB" data-template-id="5419b732fbfb950b10de65e5" data-businessunit-id="58f3a4e60000ff0005a097e6" data-style-height="24px" data-style-width="100%" data-theme="light" data-font-family="Poppins" data-text-color="#000000">
			<a href="https://uk.trustpilot.com/review/eggfreecake.co.uk" target="_blank" rel="noopener">Trustpilot</a>
		</div>
		<!-- End TrustBox widget -->
	</div>
</div>
<script>
	requirejs(['jquery'], function ($) {
		$('.trustpilot-header .trustpilot-widget').on('click', function(){
			window.location = '<?=$block->getUrl("reviews") ?>';
		});
	});
</script>