<div class="section-trustpilot-carousel">
	<!-- TrustBox widget - Carousel -->
	<div class="trustpilot-widget" data-locale="en-GB" data-template-id="53aa8912dec7e10d38f59f36" data-businessunit-id="63358bdddfcceb25ae7279e9" data-style-height="140px" data-style-width="100%" data-theme="light" data-stars="3,4,5" data-review-languages="en" data-font-family="Poppins">
		<a href="https://uk.trustpilot.com/review/cakebox.com" target="_blank" rel="noopener">Trustpilot</a>
	</div>
	<!-- End TrustBox widget -->
	<!-- TrustBox widget - Slider -->
	<div class="trustpilot-widget" data-locale="en-GB" data-template-id="54ad5defc6454f065c28af8b" data-businessunit-id="63358bdddfcceb25ae7279e9" data-style-height="240px" data-style-width="100%" data-theme="light" data-stars="3,4,5" data-review-languages="en">
	  <a href="https://uk.trustpilot.com/review/cakebox.com" target="_blank" rel="noopener">Trustpilot</a>
	</div>
	<!-- End TrustBox widget -->
</div>