<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Update Cart'); ?>
<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart update">
        <fieldset class="fieldset">
            <?php if ($block->shouldRenderQuantity()): ?>
                <div class="field qty">
                    <label class="label" for="qty"><span>
                            <?= $block->escapeHtml(__('Qty')) ?>
                        </span></label>
                    <div class="control">
                        <div class="less" style="cursor:pointer">-</div>
                        <input type="number" name="qty" id="qty" min="0" value=""
                            title="<?= $block->escapeHtmlAttr(__('Qty')) ?>" class="input-text qty"
                            data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>" />
                        <div class="more" style="cursor:pointer">+</div>
                    </div>
                </div>
            <?php endif; ?>
            <div class="actions">
                <button type="submit" title="<?= $block->escapeHtmlAttr($buttonTitle) ?>" class="action primary tocart"
                    id="product-updatecart-button">
                    <span>
                        <?= $block->escapeHtml($buttonTitle) ?>
                    </span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </fieldset>
    </div>
    <script type="text/x-magento-init">
                {
                    "#product_addtocart_form": {
                        "validation": {},
                        "addToCart": {
                            "cartButtonId": "#product-updatecart-button",
                            "cartForm": "#product_addtocart_form"
                        }
                    }
                }
            </script>
    <script type="text/javascript">
        require(["jquery"], function ($) {
            $('.more, .less').on("click", function () {
                var $this = $(this);
                if ($this.siblings('.input-text').val() >= 1) {
                    var currentQty = $this.siblings('.input-text').val();
                    if ($this.hasClass('more')) {
                        console.log(parseInt(currentQty) + parseInt(1));
                        var newAdd = parseInt(currentQty) + parseInt(1);
                        $this.siblings('.input-text').val(newAdd);
                    } else {
                        if ($this.siblings('.input-text').val() > 1) {
                            var newAdd = parseInt(currentQty) - parseInt(1);
                            $this.siblings('.input-text').val(newAdd);
                        }
                    }
                }
            });
        });
    </script>
<?php endif; ?>