stage:
    build:
    QUALITY_PATCHES:
      - ACSD-48694
    deploy:
        REDIS_BACKEND: '\Magento\Framework\Cache\Backend\RemoteSynchronizedCache'
        MYSQL_USE_SLAVE_CONNECTION: true
        REDIS_USE_SLAVE_CONNECTION: true
        CRON_CONSUMERS_RUNNER:
            cron_run: true
            max_messages: 5000
            consumers:
                - product_action_attribute.update
                - product_action_attribute.website.update
                - exportProcessor
                - codegeneratorProcessor
                - sales.rule.update.coupon.usage
                - sales.rule.quote.trigger.recollect
                - quoteItemCleaner
                - inventoryQtyCounter
                - async.operations.all

