<?php
/**
* @author Amasty Team
* @copyright Copyright (c) 2022 Amasty (https://www.amasty.com)
* @package Store Locator for Magento 2
*/
?>
<?php
/**
 * @var \Amasty\Storelocator\Block\Location $block
 * @var \Amasty\Storelocator\Model\Location $location
 */
$locations = $block->getLocationCollection();
?>
<div class="amlocator-wrapper">
    <div class="amlocator-stores-wrapper">
        <?php foreach ($locations as $location):
            ?>
            <div class="amlocator-store-desc" name="leftLocation"
                 data-mapid="<?= $block->escapeHtml($block->getMapId()); ?>"
                 data-amid="<?= (int)$location['id']; ?>">
                <div class="amlocator-block">
                    <?php if ($baseImage = $block->getLocationImage($location)):?>
                        <div class="amlocator-image"
                             style="background-image:
                                     url('<?= $block->escapeUrl($baseImage) ?>')">
                        </div>
                    <?php endif;?>
                    <div class="amlocator-store-information"><?= $location->getStoreListHtml() ?>
                        <div style="display: none;" class="amasty_distance"
                             id="amasty_distance_<?= (int)$location['id'] ?>"><?= $block->escapeHtml(__('Distance:')) ?>
                            <span class="amasty_distance_number"></span>
                        </div>
                    </div>
                    <form class="select-location" action="<?php echo $block->escapeUrl($block->getSaveAction()) ?>" formKey ="<?php echo $block->getFormKey();?>" method="POST">
                        <input type="hidden" name="location id" value="<?= (int)$location['id'] ?>">
                        <button type="submit"><?= __("Select")?></button>
                    </form>
                </div>
                <?=
                $block->getLayout()
                    ->createBlock(\Amasty\Storelocator\Block\View\Schedule::class)
                    ->setData('location', $location)
                    ->toHtml();
                ?>
            </div>
        <?php endforeach; ?>
    </div>

    <?php if ($pager = $block->getPagerHtml()): ?>
        <div class="amlocator-pager-container"><?= /** @escapeNotVerified */ $pager; ?></div>
    <?php endif; ?>
</div>
<script type="text/javascript">
    require(["jquery"],function($) {
        $(document).ready(function() {
            var customurl = "<?php echo $this->getUrl().'deliverypopup/index/selectlocation'?>";
            $.ajax({
                url: customurl,
                type: 'POST',
                dataType: 'json',
                data: {
                    customdata1: '<?= (int)$location['id'] ?>'
                },
            complete: function(response) {             
              
                },
                error: function (xhr, status, errorThrown) {
                    console.log('Error happens. Try again.');
                }
            });
        });
    });
</script>