<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2023 Amasty (https://www.amasty.com)
 * @package Store Locator for Magento 2
 */
/**
 * @var \Amasty\Storelocator\Block\Location $block
 * @var \Amasty\Storelocator\Model\Location $location
 */
$locations = $block->getLocationCollection();
?>
<div class="amlocator-wrapper">
    <div class="amlocator-stores-wrapper">
        <?php foreach ($locations as $location):
            ?>
            <div class="amlocator-store-desc" name="leftLocation"
                 data-mapid="<?= $block->escapeHtml($block->getMapId()); ?>"
                 data-amid="<?= (int)$location['id']; ?>">
                <div class="amlocator-block amlocator-location-info">
                    <?php if ($baseImage = $block->getLocationImage($location)):?>
                        <div class="amlocator-image"
                             style="background-image:
                                     url('<?= $block->escapeUrl($baseImage) ?>')">
                        </div>
                    <?php endif;?>
                    <div class="amlocator-store-information">
    
                            <h4 class="amlocator-store-name"><?= $location->getData('name') ?></h4>
                            <span class="amlocator-icon -phone"></span>
                            <a href="tel:<?= $block->escapeHtml($location->getPhone())?>" class="amlocator-link">
                                <?= $block->escapeHtml($location->getPhone())?>
                            </a>
                            <div>
                                    <span class="amlocator-icon -email"></span>
                                    <a href="mailto:<?= $block->escapeUrl($location->getEmail())?>"
                                       class="amlocator-link"
                                       title="<?= $block->escapeHtml($location->getName()); ?>">
                                        <?= $block->escapeUrl($location->getEmail())?>
                                    </a>
                            </div>
                     
                        <div style="display: none;" class="amasty_distance"
                             id="amasty_distance_<?= (int)$location['id'] ?>"><?= $block->escapeHtml(__('Distance:')) ?>
                            <span class="amasty_distance_number"></span>
                        </div>
                    </div>
                </div>
                <?php if ($location->getShowSchedule() && $location->getScheduleString()): ?>
                    <?= $block->getScheduleHtml($location) ?>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
    </div>

    <?php if ($pager = $block->getPagerHtml()): ?>
        <div class="amlocator-pager-container"><?= /** @escapeNotVerified */ $pager; ?></div>
    <?php endif; ?>
</div>
