<div class="amlocator-block -separator"><hr class="hr"></div>
<div class="form-conatiner-contact">
	<form class="form enquriy bond_recaptcha" action="<?= $block->getBaseUrl() ?>customerinquiry/inquiry/save" id="contact-form" method="post" data-mage-init='{"validation": {}}'>
		
	    <fieldset class="fieldset">
		   <div class="field name">
			   <div class="control">
					<input name="name" id="name" title="Name" placeholder="<?= __('Your Name') ?>" value="" class="input-text required-entry" type="text" data-validate='{"required":true}'>
			   </div>
		   </div>
		   <div class="field email">
			  <div class="control">
					<input name="email" id="email" title="Email" placeholder="<?= __('Your Email') ?>" class="input-text" type="email" required="true">
			  </div>
		   </div>
		   <div class="field email">
			   <div class="control">
					<input name="confirm_email" id="confirm_email" title="Confirm Email" placeholder="<?= __('Confirm Email') ?>" class="input-text" type="email" 
                    data-validate="{required:true, 'validate-email':true, equalTo:'#email'}">
			   </div>
		   </div>
		   <div class="field enquiry">
			   <div class="control">
				   <select id="enquiry-dropdown" name="enquiry_type" class="select valid" placeholder="Enquiry Type" data-validate='{"required":true}'>
						<option value="" disabled="" selected="" hidden=""><?= __('Enquiry Type') ?></option>
						<option value="Delivery"><?= __('Delivery') ?></option>
						<option value="Order (Incl. cancellation)"><?= __('Order (Incl. cancellation)') ?></option>
						<option value="Photo upload"><?= __('Photo upload') ?></option>
						<option value="Cakes"><?= __('Cakes') ?></option>
						<option value="Wedding Cakes"><?= __('Wedding Cakes') ?></option>
						<option value="Complaint"><?= __('Complaint') ?></option>
						<option value="Franchise"><?= __('Franchise') ?></option>
						<option value="Other"><?= __('Other') ?></option>
					</select>
			   </div>
		   </div>              
              <!-- error messages- -->
               <div class="delivery-message messageerros" style="display: block;">
              
               	<p><?= __('Please note, we DO NOT offer a delivery service. When placing your order in store or online, you will need to specify a collection date and time') ?>.&nbsp;</p>
               </div>
               <div class="order-message messageerros" style="display: none;">
              	 
                 <p><?= __('If you have any questions regarding an order you have placed, please contact your local branch directly to ensure the quickest response. Please have your order number at hand so we can help resolve your query as quickly as possible. You can find contact details for your local branch above') ?>.</p>
               </div>
               <div class="photo-message messageerros" style="display: none;">
              	
                 <p><?= __('If you have questions regarding your photo cake, please contact your local branch directly to ensure the quickest response. You can find their contact details above. Please have your order number at hand so we can help resolve your query as quickly as possible. You can find contact details for your local branch above') ?>.</p>
               </div>
               <div class="cakes-message messageerros" style="display: none;">
              	
                 <p><?= __('If you have any questions regarding a cake you have seen on our website, please contact your local branch directly to ensure the quickest response. Our friendly staff will be more than happy to help') ?>.</p>
                 <p><?= __('You can find contact details for your local branch above') ?>.&nbsp;</p>
               </div>
               <div class="wedding-message messageerros" style="display: none;">
              	 
                 <p><?= __('If you have any questions regarding a wedding cake you have seen on our website, please contact your local branch directly to ensure the quickest response. Our friendly staff will be more than happy to help') ?>.<br><?= __('You can find contact details for your local branch above') ?>.</p>
               </div>
               <div class="complaints-message messageerros" style="display: none;">
              		<p><?= __('We are sorry you have reason to complain. We pride ourselves on excellent customer service and will endeavour to help put things right. Please send a detailed email to') ?> <a href="mailto:customerservices@eggfreecake.co.uk">CUSTOMERSERVICES@EGGFREECAKE.CO.UK</a>&nbsp;<?= __('to ensure the quickest response') ?>.</p>                          	 
               </div>
               <div class="franchise-message messageerros" style="display: none;">
              		<p><?= __('If you are interested in becoming a Franchisee') ?>, <a href="#"><?= __('click here') ?></a> <?= __('to download the application, and send the completed form to') ?> <a href="mailto:franchiseenquiries@eggfreecake.co.uk">franchiseenquiries@eggfreecake.co.uk</a></p>                          	 
               </div>              
              
               <!-- error messages- -->
              
		   <div class="field message">
			   <div class="control">
				 	<textarea name="message" id="message" placeholder="<?= __('Message') ?>" title="<?= __('Message') ?>" class="input-text" cols="5" rows="3" data-validate='{"required":true}'></textarea>
			   </div>
		   </div>
	   </fieldset> 
	   <div class="actions-toolbar">
		   <div class="primary">
			   <input type="hidden" name="hideit" id="hideit" value="">
			   <button type="submit" title="<?= __('Submit Now') ?>" class="action submit primary" disabled="disabled">
					<span><?= __('Submit Now') ?></span>
			   </button>
		   </div>
	   </div>
   </form>
</div>
<script type="text/javascript">
	require(['jquery'], function($) {
   
        $(document).ready(function() {

            var dropdown = document.getElementById("enquiry-dropdown");
            dropdown.onchange = function(event) {
                if (dropdown.value == "Delivery") {
                    $(".order-message, .photo-message, .cakes-message, .wedding-message, .complaints-message, .franchise-message").fadeOut("slow", function() {});
                    $(".delivery-message").delay(300).fadeIn("slow", function() {});
                    $('.action.submit.primary').attr("disabled", true);
                }
                if (dropdown.value == "Order (Incl. cancellation)") {
                    $(".delivery-message, .photo-message, .cakes-message, .wedding-message, .complaints-message, .franchise-message").fadeOut("slow", function() {});
                    $(".order-message").delay(300).fadeIn("slow", function() {});
                    $('.action.submit.primary').attr("disabled", true);
                }
                if (dropdown.value == "Photo upload") {
                    $(".delivery-message, .order-message, .cakes-message, .wedding-message, .complaints-message, .franchise-message").fadeOut("slow", function() {});
                    $(".photo-message").delay(300).fadeIn("slow", function() {});
                    $('.action.submit.primary').attr("disabled", true);
                }
                if (dropdown.value == "Cakes") {
                    $(".delivery-message, .order-message, .photo-message, .wedding-message, .complaints-message, .franchise-message").fadeOut("slow", function() {});
                    $(".cakes-message").delay(300).fadeIn("slow", function() {});
                    $('.action.submit.primary').attr("disabled", true);
                }
                if (dropdown.value == "Wedding Cakes") {
                    $(".delivery-message, .order-message, .photo-message, .cakes-message, .complaints-message, .franchise-message").fadeOut("slow", function() {});
                    $(".wedding-message").delay(300).fadeIn("slow", function() {});
                    $('.action.submit.primary').attr("disabled", true);
                }
                if (dropdown.value == "Complaint") {
                    $(".delivery-message, .order-message, .photo-message, .cakes-message, .wedding-message, .franchise-message").fadeOut("slow", function() {});
                    $(".complaints-message").delay(300).fadeIn("slow", function() {});
                    $('.action.submit.primary').attr("disabled", true);
                }
                if (dropdown.value == "Franchise") {
                    $(".delivery-message, .order-message, .photo-message, .cakes-message, .wedding-message, .complaints-message").fadeOut("slow", function() {});
                    $(".franchise-message").delay(300).fadeIn("slow", function() {});
                    $('.action.submit.primary').attr("disabled", true);
                }
                if (dropdown.value == "Other") {
                    $(".delivery-message, .order-message, .photo-message, .cakes-message, .wedding-message, .complaints-message, .franchise-message").fadeOut("slow", function() {});
                    $('.action.submit.primary').removeAttr("disabled", true);
                }
            }
        });
    });
</script>