<?php
/**
 * @var $block \X247Commerce\Nutritics\Block\Product\View\Nutritics
 */
?>
<?php
$nutriticsInfos = $block->getProductNutriticsInfoInDb();
$htmlIngredients = '';
$htmlAllergens = '';
$html = '';
?>
<div class="ingredient-allergen-info-wraper">
    <?php if (empty($nutriticsInfos)): ?>
        <?= __('For ingredients and allergen information, please select all required options') ?>.
    <?php else: ?>
    <div class="ingredient-allergen-info">
        <?php foreach ($nutriticsInfos as $info): ?>
            <?php if ($info['attribute_code'] == 'allergens'): ?>
                    <div class="allergens-info-detail">
                        <?php $allergens = json_decode($info['value'], true) ?>
                        <?php if ($allergens['contains']) : ?>
                            <?php $htmlAllergens .= '<p> 
                                <span class="allergens-title">' . __('This product contains the following allergens') . ': </span>
                                <span class="allergens-detail contains">' . implode(', ', $allergens['contains']) . '</span></p>'; ?>
                        <?php endif?>
                        <?php if ($allergens['maycontain']) : ?>
                            <?php $htmlAllergens .= '<p>
                                <span class="allergens-title">'. __('This product may contains the following allergens') .': </span>
                                <span class="allergens-detail maycontain">'. implode(', ', $allergens['maycontain']) .'</span></p>'; ?>
                        <?php endif?>
                        <?php if ($allergens['freefrom']) : ?>
                            <?php $htmlAllergens .= '<p>
                                <span class="allergens-title">'. __('This product free from the following allergens') .': </span>
                                <span class="allergens-detail freefrom">'. implode(', ', $allergens['freefrom']) .'</span></p>'; ?>
                        <?php endif?>
                        <?php if ($allergens['suitablefor']) : ?>
                            <?php $htmlAllergens .= '<p>
                                <span class="allergens-title">'. __('This product suitablefor the following') .': </span>
                                <span class="allergens-detail suitablefor">'. implode(', ', $allergens['suitablefor']) .'</span></p>'; ?>
                        <?php endif?>
                    </div>
            <?php endif ?>
            <?php if ($info['attribute_code'] == 'quid'): ?>
                <?php $htmlIngredients .= '<div class="ingredient-info-detail"> <span class="ingredients-title">' . __('Ingredients') 
                                            . ': </span>' . $info['value'] . '</div>'; ?>
            <?php endif ?>
        <?php endforeach ?>
        <?= $html .= $htmlAllergens.$htmlIngredients ?>
    </div>
    <?php endif ?>
</div>