<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Generic.WhiteSpace.ScopeIndent.IncorrectExact
// phpcs:disable Magento2.Security.LanguageConstruct.DirectOutput
?>
<?php
    $_category  = $block->getCurrentCategory();
    $_imgHtml   = '';
?>


<?php if ( $_imgUrl = $block->getImage()->getUrl($_category) ): ?>
    <style type="text/css">
        .catalog-category-view .category-header {
            background-image: url('<?php echo $block->escapeUrl($_imgUrl) ?>');
        }
    </style>
<?php endif ?>