<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/** @var $block \Magento\Swatches\Block\Product\Renderer\Configurable */
/** @var \Magento\Swatches\ViewModel\Product\Renderer\Configurable $configurableViewModel */
$configurableViewModel = $block->getConfigurableViewModel();
$product = $block->getProduct();
$helperSwatch = $this->helper('X247Commerce\Products\Helper\Data');
$shapeImage = false;
$label = false;

if ( $product->getData('shape') ) {
    $shapeImage = $helperSwatch->getDataSwatchSponge($product->getData('shape'));
    $label = $product->getResource()->getAttribute('shape')->getFrontend()->getValue($product);
}
?>
<div class="swatch-opt" data-role="swatch-options"></div>

<script type="text/x-magento-init">
    {
        "[data-role=swatch-options]": {
            "Magento_Swatches/js/swatch-renderer": {
                "jsonConfig": <?= /* @noEscape */ $swatchOptions = $block->getJsonConfig() ?>,
                "jsonConfig1HourCollection": <?= $block->getJsonConfigWith1HourCollection() ?>,
                "jsonSwatchConfig": <?= /* @noEscape */ $swatchOptions = $block->getJsonSwatchConfig() ?>,
                "mediaCallback": "<?= $block->escapeJs($block->escapeUrl($block->getMediaCallback())) ?>",
                "getNutriticsUrl": "<?= /* @escapeNotVerified */ $block->getUrl('nutritics/ajax/GetNutriticsInfo') ?>",
                "parentProductId": "<?= /* @escapeNotVerified */ $product->getId() ?>",
                "gallerySwitchStrategy": "<?= $block->escapeJs($block->getVar('gallery_switch_strategy', 'Magento_ConfigurableProduct')) ?: 'replace'; ?>",
                "jsonSwatchImageSizeConfig": <?= /* @noEscape */ $block->getJsonSwatchSizeConfig() ?>,
                "showTooltip": <?= $block->escapeJs($configurableViewModel->getShowSwatchTooltip()) ?>,
                "shapeImage": "<?= $shapeImage ?>",
                "shapeLabel": "<?= $label ?>"
            }
        },
        "*" : {
            "Magento_Swatches/js/catalog-add-to-cart": {}
        },
        ".swatch-opt": {
            "Magento_Swatches/js/custom": {}
        }
    }
</script>
