<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

$product = $block->getProduct();
$sku = $product->getSku();
// $productRangeSkus = $product->getRangeSkus();
$productRangeSkus='';
$productTypeInstance = $product->getTypeInstance();
if (method_exists($productTypeInstance, 'getUsedProducts')) {
    $usedProducts = $productTypeInstance->getUsedProducts($product);
    foreach ($usedProducts  as $child) {
        $productRangeSkus .= $child->getSku().',';
    }
}

$productJointSkus = $productRangeSkus ? $sku . ',' . $productRangeSkus : $sku;
?>
<!-- TrustBox widget - Product Mini -->
<div class="product-reviews-summary">
	<div class="trustpilot-widget" data-locale="en-GB" data-template-id="54d39695764ea907c0f34825" data-businessunit-id="63358bdddfcceb25ae7279e9" data-style-height="24px" data-style-width="100%" data-theme="light" data-sku="<?= $productJointSkus ?>" data-scroll-to-list="true" data-style-alignment="left">
		<a href="https://uk.trustpilot.com/review/cakebox.com" target="_blank" rel="noopener">Trustpilot</a>
	</div>
</div>
<!-- End TrustBox widget -->