<?php
/*** Copyright © Ulmod. All rights reserved. **/
?> 
<?php
/**
 * @var $block Ulmod\Productinquiry\Block\ProductinquiryForm
 */
?>
<?php if ($block->isRecaptchaV2CheckboxEnabled()): ?>
<script  
src='//www.google.com/recaptcha/api.js?onload=reCaptchaCallbackUmProdinquiry&render=explicit&hl=en' 
async defer></script>
<script>
    var canSubmit = false;
    function reCaptchaVerifyUmProdinquiry(response) {
        if (response) {
            canSubmit = true;
        }
    }
    function reCaptchaCallbackUmProdinquiry () {
        grecaptcha.render(document.getElementById('g-recaptcha-response-umprodinquiry'), {
        'sitekey': '<?= $block->escapeHtml($block->getRecaptchaSiteKey());?>',
        'callback': reCaptchaVerifyUmProdinquiry,
        'theme': 'light'
        });  
    }
     document.getElementById('um-prodinq-form').addEventListener('submit',function(e){
     if (!canSubmit) {
       jQuery('#g_recaptcha-error-umprodinquiry').show();
       e.preventDefault();
     }
    });
</script>
<?php endif; ?>
