<div id="custom-popup-modal" style="display: none">
    <div class="col-sm-6">
        <div class="static_content">
            <p class="content"><?php echo $block->getSuccessCartMessage() ?></p>
        </div>
    </div>
</div>
<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/modal'
    ],function($,modal) {
        var options = {
            type: 'popup',
            responsive: true,
        };
        var popup = modal(options, $('#custom-popup-modal'));
        $.ajax({
            url: '<?php echo $block->getUrl("cakeboxoffer/index/post") ?>',
            dataType: 'json',
            data: {'form_key':$.cookie('form_key')},
            type : "post"
        }).done(function (response) {
            if (response.result) {
                $('#custom-popup-modal').modal('openModal');
            }
        });
    });
</script>

