<?php
$productData = [
	'releated' => [
		'products' => $block->getProduct()->getRelatedProductCollection()->addAttributeToSelect('*'),
		'label' => __('Releated Product')
	],
	'upsell' => [
		'products' => $block->getProduct()->getUpSellProductCollection()->addAttributeToSelect('*'),
		'label' => __('UpSell Product')
	],
	'crosssell' => [
		'products' => $block->getProduct()->getCrossSellProductCollection()->addAttributeToSelect('*'),
		'label' => __('CrossSell Product')
	],
];
?>
<?php if ( count( $block->getProduct()->getCrossSellProductCollection() ) > 0 || count( $block->getProduct()->getUpSellProductCollection() ) > 0 || count( $block->getProduct()->getCrossSellProductCollection() ) > 0 ): ?>
	<div class="addtocart-sidebar">
		<div class="addedtocart-wrapper">
			<div class="suggest-products">
				<?php foreach ($productData as $tab => $data): ?>
					<?php if ( count( $data['products'] ) > 0 ): ?>

						<div class="tab product-tab">
							<div class="tab-title">
								<?php echo $data['label']; ?>
							</div>
							<div class="tab-content" style="display: none;">
								<?php foreach ($data['products'] as $product): ?>
									<div class="item">
										<div class="item-info">
											<div class="item-image">
												<?php
													$imageDisplayArea = 'product_more_to_add';
													$productImage = $block->getImage($product, $imageDisplayArea);
												?>
												<a href="<?= $product->getProductUrl() ?>"
													class="product photo product-item-photo"
													tabindex="-1">
													<?= $productImage->toHtml() ?>
												</a>
											</div>
											<div class="item-name">
												<a class="product-item-link" href="<?= $product->getProductUrl() ?>">
													<?php echo $product->getName(); ?>
												</a>
												<div class="product-price">
													<?= /* @noEscape */ $block->getProductPrice($product) ?>
												</div>
											</div>
										</div>
											<div class="item-action">
													<?php $postParams = $block->getAddToCartPostParams($product); ?>
													<form data-role="tocart-form"
														  data-product-sku="<?= $product->getSku() ?>"
														  action="<?= $postParams['action'] ?>"
														  method="post"
														  class="popup-tocart tocart-form tocart-<?= $product->getId() ?>">
														<?php $optionsData = $block->getViewModel()->getOptionsData($product); ?>
														<?php foreach ($optionsData as $optionItem): ?>
															<input type="hidden"
																   name="<?= $optionItem['name'] ?>"
																   value="<?= $optionItem['value'] ?>">
														<?php endforeach; ?>
														<input type="hidden"
															   name="product"
															   value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
														<input type="hidden"
															   name="<?= /* @noEscape */ \Magento\Framework\App\Action\Action::PARAM_NAME_URL_ENCODED ?>"
															   value="<?=
															   /* @noEscape */ $postParams['data'][\Magento\Framework\App\Action\Action::PARAM_NAME_URL_ENCODED]
																?>">
														<?= $block->getBlockHtml('formkey') ?>
														<button type="submit"
																title="<?= __('Add to Cart') ?>"
																class="action tocart primary"
																disabled>
															<span><?= __('Add to Cart') ?></span>
														</button>
													</form>
											</div>
									</div>
								<?php endforeach ?>
							</div>
						</div>
						<script type="text/x-magento-init">
						{
							"[data-role=tocart-form], .form.map.checkout": {
								"catalogAddToCart": {
									"product_sku": "<?= $escaper->escapeJs($product->getSku()) ?>"
								}
							}
						}
						</script>
					<?php endif ?>
				<?php endforeach ?>

			</div>
		</div>
	</div>
<?php endif ?>
