<?php
/**
 * @var X247Commerce\StoreLocator\Block\Catalog\Product\SuggestClosestLocation $block
 */
?>
<div class="closest-location-container">
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "X247Commerce_StoreLocator/js/product/view/suggest-closest-location": {
                "suggestClosestLocationAjaxUrl": "<?= $block->getSuggestClosestLocationAjaxUrl() ?>"
            }
        }
    }
</script>
