<?php
/**
* @author Amasty Team
* @copyright Copyright (c) 2022 Amasty (https://www.amasty.com)
* @package Store Locator for Magento 2
*/
?>
<?php
/** @var \Amasty\Storelocator\Model\Location $location */
/** @var \Amasty\Storelocator\Block\View\Location $block */
$location = $block->getCurrentLocation();
$location->setTemplatesHtml();

$galleryImages = $block->getLocationGallery();

$adressString = $location->getCity() . ', ' . $location->getAddress() . ', ' . $location->getZip();

$blockLocationCollection= $block->getLayout()->createBlock('\Amasty\Storelocator\Block\Location');
$allLocation = $blockLocationCollection->getLocationCollection();
$imageHelper = $this->helper(\Magento\Catalog\Helper\Image::class);
$placeholderImageUrl = $imageHelper->getDefaultPlaceholderUrl('image');
?>
<div class="amlocator-location-main">
    <div class="amlocator-location-container">
        <div class="amlocator-column -left">
            <div class="amlocator-block -route amlocator-route-creator" data-amlocator-js="route-creator">
                <div class="amlocator-modes">
                    <input class="amlocator-mode" id="driving-mode" name="travel-mode" data-amlocator-js="travel-mode"
                           type="radio" value="DRIVING" checked/>
                    <label class="amlocator-label -driving" for="driving-mode"></label>
                    <input class="amlocator-mode" id="transit-mode" name="travel-mode" data-amlocator-js="travel-mode"
                           type="radio" value="TRANSIT"/>
                    <label class="amlocator-label -transit" for="transit-mode"></label>
                    <input class="amlocator-mode" id="walking-mode" name="travel-mode" data-amlocator-js="travel-mode"
                           type="radio" value="WALKING"/>
                    <label class="amlocator-label -walking" for="walking-mode"></label>
                    <input class="amlocator-mode" id="bicycling-mode" name="travel-mode" data-amlocator-js="travel-mode"
                           type="radio" value="BICYCLING"/>
                    <label class="amlocator-label -bicycling" for="bicycling-mode"></label>
                </div>

                <div class="amlocator-addresses">
                <div class="amlocator-route-icon">
                    <span class="amlocator-icon -start"></span>
                    <span class="amlocator-icon -dot"></span>
                    <span class="amlocator-icon -dot"></span>
                    <span class="amlocator-icon -dot"></span>
                    <span class="amlocator-icon -end"></span>
                </div>
                    <div class="amlocator-inputs">
                        <input class="amlocator-address -start" data-amlocator-js="origin-point" type="text"/>
                        <input class="amlocator-address -end"
                               data-amlocator-js="destination-point"
                               type="text"
                               readonly
                               value="<?= $block->escapeHtml($adressString); ?>" />
                    </div>
                    <input class="amlocator-swap" id="swap-mode" data-amlocator-js="swap-mode" type="checkbox" />
                    <label class="amlocator-label" for="swap-mode"></label>
                </div>
            </div>

            <div class="amlocator-block -directions amlocator-directions-wrapper" data-amlocator-js="directions"
                 style="display: none;">
                <div class="amlocator-collapse-title" data-amlocator-js="collapse-trigger">
                    <span><?= $block->escapeHtml(__('Directions')); ?></span>
                    <span class="amlocator-arrow" data-amlocator-js="collapse-indicator"></span>
                </div>
                <div class="amlocator-directions-container" data-amlocator-js="collapse-content">
                    <div data-amlocator-js="directions-panel"></div>
                </div>
            </div>

            <div class="amlocator-block -separator"><hr class="hr"/></div>
            <div class="amlocator-block-image">
                <div class="half-height">
                    <img src="https://www.eggfreecake.co.uk/media/bond_storelocator/storelocator/image//a/l/aldershot.jpg" alt="29 Wellington Street">
                </div>                    
                <div class="half-height cta-shopping">                        
                    <h4 class="order-online"><?= __('ORDER ONLINE') ?></h4>                        
                    <a href="<?= $block->getBaseUrl() ?>cakes.html">
                        <span class="button-view-cake"><?= __('VIEW CAKES') ?></span>
                    </a>
                    
                </div>                    
            </div>
            <div class="amlocator-block amlocator-location-info">
                <?= $block->getChildHtml('extra_info') ?>
                <div class="amlocator-block">
                    <span><?= $block->escapeHtml(__('Zip: '))?></span>
                    <span><?= $block->escapeHtml($location->getZip())?></span>
                </div>
                <div class="amlocator-block">
                    <span><?= $block->escapeHtml(__('Country: '))?></span>
                    <span><?= $block->escapeHtml($block->getLocationCountryName($location->getCountry()))?></span>
                </div>
                <?php if ($stateName = $block->getStateName($location->getState())): ?>
                    <div class="amlocator-block">
                        <span><?= $block->escapeHtml(__('State: '))?></span>
                        <span><?= $block->escapeHtml($stateName)?></span>
                    </div>
                <?php endif;?>
                <div class="amlocator-block">
                    <span><?= $block->escapeHtml(__('City: '))?></span>
                    <span><?= $block->escapeHtml($location->getCity())?></span>
                </div>
                <div class="amlocator-block">
                    <span><?= $block->escapeHtml(__('Address: '))?></span>
                    <span class="amlocator-text -bold"><?= $block->escapeHtml($location->getAddress())?></span>
                </div>
                <div class="amlocator-block -contact">
                    <?php if (!empty($location->getWebsite())): ?>
                        <div class="amlocator-block">
                            <span class="amlocator-icon -website"></span>
                            <a href="<?= $block->escapeUrl($location->getWebsite())?>"
                               class="amlocator-link"
                               title="<?= $block->escapeHtml($location->getName()); ?>"
                               target="_blank"><?= $block->escapeUrl($location->getWebsite())?></a>
                        </div>
                    <?php endif;
                    if (!empty($location->getPhone())): ?>
                        <div class="amlocator-block">
                            <span class="amlocator-icon -phone"></span>
                            <a href="tel:<?= $block->escapeHtml($location->getPhone())?>" class="amlocator-link">
                                <?= $block->escapeHtml($location->getPhone())?>
                            </a>
                        </div>
                    <?php endif;
                    if (!empty($location->getEmail())): ?>
                        <div class="amlocator-block">
                            <span class="amlocator-icon -email"></span>
                            <a href="mailto:<?= $block->escapeUrl($location->getEmail())?>"
                               class="amlocator-link"
                               title="<?= $block->escapeHtml($location->getName()); ?>">
                                <?= $block->escapeUrl($location->getEmail())?>
                            </a>
                        </div>
                    <?php endif;?>
                </div>
                <div class="amlocator-block">
                    <a class="amlocator-link" data-amlocator-js="locator-panorama">Street View</a>
                </div>
            </div>

            <div class="amlocator-block">
                <?= $block->getChildBlock('amasty_store_locator_schedule')->setData('location', $location)->toHtml(); ?>
            </div>

            <?php if (count($galleryImages)): ?>
                <div class="amlocator-block -separator"><hr class="hr"/></div>
                <div class="amlocator-block amlocator-location-gallery">
                    <span class="amlocator-title"><?= $block->escapeHtml(__('Photos'))?></span>
                    <div class="amlocator-wrapper" data-amlocator-js="locator-gallery">
                    <?php foreach ($galleryImages as $image): ?>
                        <a class="amlocator-link"
                           href="<?= $block->escapeHtml($image['path']) ?>"
                           data-amlocator-js="location-image"
                           data-fancybox="gallery">
                            <img class="amlocator-image"
                                 title="<?= $block->escapeHtml($location->getName()) ?>"
                                 src="<?= $block->escapeHtml($image['path']) ?>"/>
                        </a>
                    <?php endforeach; ?>
                    </div>
                </div>
            <?php endif;?>
            <?= $block->getLayout()
                ->createBlock(\Amasty\Storelocator\Block\View\Reviews::class)
                ->setData('location', $location)
                ->toHtml(); ?>
            <?= $block->getChildHtml('customer_inquiry_form'); ?>
        </div>

        <div class="amlocator-column -right">
            <div class="amlocator-block -map" data-amlocator-js="location-map"></div>
            <?= $block->getChildBlock('amasty_store_location_page_attributes')
                ->setData('location', $location)
                ->toHtml();
            ?>
            <div class="amlocator-description-grey">
                <?= /** @escapeNotVerified */ $location->getLocationDescription() ?>
            </div>

            <div class="amlocator-block-closed">
               <h3 class="close-title">Queen Funeral Closed</h3>               
               <div class="intro-text">
                  <p>
                    <strong>
                        Closed: 19/9/2022
                    </strong>
                  </p>
               </div>               
               <div class="opening-custom"></div>
            </div>
            <div class="amlocator-store-list">
                <h3 class="branch-group"><?= __('Branches') ?></h3>

                <div class="amlocator-stores-collection">
                    <?php foreach ($allLocation as $item): ?>
                        <a class="amlocator-store-link" href="<?= $item->getLocationUrl() ?>">
                            <div class="amlocator-block-store">
                                <?php if ($baseImage = $blockLocationCollection->getLocationImage($item)):?>
                                    <div class="amlocator-store-image"
                                         style="background-image:
                                                 url('<?= $block->escapeUrl($baseImage) ?>')">
                                    </div>
                                <?php else: ?>
                                    <img class="amlocator-store-image" src="<?= $placeholderImageUrl ?>">
                                    </img>
                                <?php endif;?>
                                <h4 class="amlocator-store-name"><?= $item->getData('name') ?></h4>
                            </div>
                        </a>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    require([
        'jquery',
        'Amasty_Storelocator/js/location-view',
        'domReady!',
        'https://maps.googleapis.com/maps/api/js?libraries=places&key=<?= $block->escapeHtml(
            $block->configProvider->getApiKey()
        ); ?>'
    ], function ($) {
        $('[data-amlocator-js="location-map"]').amLocationPage({
            locationData: {
                lat: <?= (float)$location->getLat() ?>,
                lng: <?= (float)$location->getLng() ?>,
                marker_url: '<?= $block->escapeHtml($location->getMarkerMediaUrl()) ?>'
            }
        });
    });
</script>
