<?php /** @var $block \X247Commerce\Checkout\Block\Cart\StoreLocator */ ?>
<?php /** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */ ?>
<div id="block-ams-store-locator_wrapper"
     class="block ams-store-locator"
>
    <div id="block-ams-store-locator"
         data-bind="scope:'blockStoreLocator'"
         class="content"
         data-role="content"
         aria-labelledby="block-shipping-heading"
    >
        <!-- ko template: getTemplate() --><!-- /ko -->
        <script type="text/x-magento-init">
            {
                "#block-ams-store-locator": {
                    "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
                }
            }
        </script>
    </div>
</div>
