<?php /** @var $block \X247Commerce\Checkout\Block\Cart\StoreLocator */ ?>
<?php /** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */ ?>
<div id="block-store-locator"
     class="block store-locator"
>
    <div id="block-store-locator"
         data-bind="scope:'block-store-locator'"
         class="content"
         data-role="content"
         aria-labelledby="block-shipping-heading"
    >
        <!-- ko template: getTemplate() --><!-- /ko -->
        <script type="text/x-magento-init">
            {
                "#block-store-locator": {
                    "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
                }
            }
        </script>
<?php 
$serializedCheckoutConfig = /* @noEscape */ $block->getSerializedCheckoutConfig();
$serializedStoreLocationData = /* @noEscape */ $block->getStoreLocationData();
$scriptString = <<<script
            window.storeLocationData = {$serializedStoreLocationData};
            window.checkoutConfig = {$serializedCheckoutConfig};
            window.customerData = window.checkoutConfig.customerData;
            window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
            require([
                'mage/url',
                'Magento_Ui/js/block-loader'
            ], function(url, blockLoader) {
                blockLoader(
                    "{$block->escapeJs($block->escapeUrl($block->getViewFileUrl('images/loader-1.gif')))}"
                );
                return url.setBaseUrl('{$block->escapeJs($block->escapeUrl($block->getBaseUrl()))}');
            })
script;
?>
        <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
    </div>
</div>
