<?php
if ($bottomDescription = $block->getCurrentCategory()->getBottomDescription()): ?>
    <div id="category-bottom-description" class="category-bottom-description">
        <div id="bottom-description-inner">
            <?= /* @escapeNotVerified */ $this->helper('Magento\Catalog\Helper\Output')->categoryAttribute(
                $block->getCurrentCategory(), $bottomDescription, 'bottom_description'
            ) ?>
        </div>
        <br />
        <a id="bottom-read-more" href="#" style="display: block;"><?= __('Read More') ?></a>
    </div>

    <script>
        var BDElem = document.getElementById("bottom-description-inner"); //Bottom description elem
        var lh = parseInt(getComputedStyle(BDElem).lineHeight); // line height
        var BRM = document.getElementById('bottom-read-more'); // Bottom read more

        if (BDElem.clientHeight > lh * 3) {
            BRM.style.display = "block";
            BDElem.style.overflow = "hidden";
            BDElem.style.maxHeight = lh * 3 + "px";
        }

        BRM.addEventListener("click", function(event) {
            event.preventDefault();
            if (BRM.textContent === '<?= __("Read More") ?>') {
                BRM.textContent = '<?= __("Read Less") ?>';
                BDElem.style.maxHeight = "none";
            } else {
                BRM.textContent = '<?= __('Read More') ?>';
                BDElem.style.maxHeight = lh * 3 + "px";
            }
        });
    </script>
<?php endif; ?>
