<?php
// @codingStandardsIgnoreFile
$_helper = $this->helper('WeltPixel\GA4\Helper\Data');
$scriptAdditionalTag = '';
if ($_helper->isDevMoveJsBottomEnabled()) {
    $scriptAdditionalTag = ' exclude-this-tag="text/x-magento-template"';
}
?>
<?php if ($block->isEnabled()) : ?>
    <?php $dataLayerObject = $block->getDataLayerAsJson(); ?>
    <script<?=$scriptAdditionalTag?>>
        window.getWpGA4Cookie = function(name) {
            match = document.cookie.match(new RegExp(name + '=([^;]+)'));
            if (match) return decodeURIComponent(match[1].replace(/\+/g, ' ')) ;
        };

        window.dataLayer = window.dataLayer || [];
        <?php if ($dataLayerObject != '[[]]') : ?>
        var dl4Objects = <?php echo $dataLayerObject; ?>;
        for (var i in dl4Objects) {
            window.dataLayer.push({ecommerce: null});
            window.dataLayer.push(dl4Objects[i]);
        }
        <?php endif; ?>
        var wpGA4Cookies = [<?php echo $block->getWpGA4CookiesForJs(); ?>];
        wpGA4Cookies.map(function(cookieName) {
            var cookieValue = window.getWpGA4Cookie(cookieName);
            if (cookieValue) {
                var dl4Object = {};
                dl4Object[cookieName.replace('wp_ga4_', '')] = cookieValue;
                window.dataLayer.push(dl4Object);
            }
        });
    </script>
<?php endif; ?>
<?php //SPTCAK-1
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $action = $objectManager->get(\Magento\Framework\App\Action\Action::class);

    if($action->getRequest()->getFullActionName() == 'checkout_onepage_success') { 
        $checkoutSession = $objectManager->get(\Magento\Checkout\Model\Session::class);
        $order = $checkoutSession->getLastRealOrder();

        if ($order) {
            $orderId = $order->getIncrementId(); ?>
            <!-- Event snippet for Purchase conversion page -->
            <script>
            gtag('event', 'conversion', {
              'send_to': 'AW-699685976/LuoLCPOwjpEYENi40c0C',
              'value': 1.0,
              'currency': 'GBP',
              'transaction_id': '<?php echo $orderId;?>'
            });
            </script>
    <?php 
        }
    }
