<?php
// @codingStandardsIgnoreFile
?>
<?php if($this->isEnabled()) : ?>
    <?php

    $helper = $this->helper('WeltPixel\GA4\Helper\Data');
    $ga4ServerSideHelper = $this->helper('WeltPixel\GA4\Helper\ServerSideTracking');
    $order = $this->getOrder();

    if ($this->isFreeOrderTrackingAllowedForGoogleAnalytics() && !($ga4ServerSideHelper->isServerSideTrakingEnabled() && $ga4ServerSideHelper->shouldEventBeTracked(\WeltPixel\GA4\Model\Config\Source\ServerSide\TrackingEvents::EVENT_PURCHASE)
        && $ga4ServerSideHelper->isDataLayerEventDisabled())) :
        $products = $this->getProducts();
    //[SPTCAK-30 adding customer info]
        $customerEmail = $order->getCustomerEmail();
        $customerPhone = $order->getShippingAddress()->getTelephone();
        $customerId = $order->getCustomerId();
        $totalOrders = 0;
        $isNewUser = true;
        if($customerId) {
            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            $orderObject = $objectManager->create('Magento\Sales\Model\Order')
            ->getCollection()
            ->addAttributeToFilter('customer_id', $customerId);
            $totalOrders = count($orderObject->getData())?count($orderObject->getData()):0;
        }
        if($totalOrders){
            $isNewUser = false;
        }
    //SPTCAK-30 END
        $purchaseData = [
            'transaction_id' => $order->getIncrementId(),
            'affiliation' => $helper->getAffiliationName(),
            'value' => number_format($this->getOrderTotal(), 2, '.', ''),
            'coupon' => (string)$order->getCouponCode(),
            'tax' => number_format($order->getTaxAmount(), 2, '.', ''),
            'shipping' => number_format($order->getShippingAmount(), 2, '.', ''),
            'currency' => $this->getCurrencyCode(),
            'total_order_count' => $this->getTotalOrderCount(),
            'total_lifetime_value' => number_format($this->getTotalLifetimeValue(), 2, '.', '')
        ];
    //SPTCAK-30
        $purchaseData['email'] = $customerEmail;
        $purchaseData['phone_number'] = $customerPhone;
        $purchaseData['new_customer'] = $isNewUser;
    //SPTCAK-30 END
        $purchaseData['items'] = $products;

        $this->setEcommerceData('purchase', $purchaseData);
        $this->setDataLayerOption('event', 'purchase');
    endif;

    if ($helper->isAdWordConversionTrackingEnabled() && $this->isFreeOrderAllowedForAdwordsConversionTracking()) :
        $this->setDataLayerOption(\WeltPixel\GA4\Model\Api\ConversionTracking::FIELD_CONVERSION_TRACKING_CONVERSION_VALUE, $this->getOrderTotal());
        $this->setDataLayerOption(\WeltPixel\GA4\Model\Api\ConversionTracking::FIELD_CONVERSION_TRACKING_ORDER_ID, $order->getIncrementId());
    endif;

    if ($helper->isAdWordsRemarketingEnabled() && $this->isFreeOrderAllowedForAdwordsRemarketing()):
        $remarketingData = [];
        $remarketingData['ecomm_pagetype'] = \WeltPixel\GA4\Model\Api\Remarketing::ECOMM_PAGETYPE_PURCHASE;
        $remarketingData['ecomm_prodid'] = $this->getProductIds();
        $remarketingData['ecomm_totalvalue'] = number_format($this->getOrderTotal(), 2, '.', '');
        $this->setDataLayerOption('google_tag_params', $remarketingData);
    endif;

    ?>
<?php endif; ?>
